FROM multiarch/ubuntu-debootstrap:arm64-bionic
RUN apt-get update -qq && \
  apt-get install -yq --no-install-suggests --no-install-recommends \
  bzip2 \
  ca-certificates \
  gcc \
  g++ \
  make \
  software-properties-common
RUN add-apt-repository -y universe && \
  apt-get update -qq && \
  apt-get install -yq libhdf5-dev
RUN find /usr/include -name "H5*.h" || true
RUN find /usr/include -name "hdf5.h" || true
WORKDIR /nanopolish
COPY . .
ENTRYPOINT ["/nanopolish/entrypoint.sh"]
